<a href="https://colab.research.google.com/github/Alex112525/Neural-Networks-with-PyTorch-course/blob/main/First_steps_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch

**PyTorch** is a machine learning framework based on the Torch library. It is used for applications such as computer vision and natural language processing. PyTorch is an open-source library developed using Torch library for python program.

*torch.nn* is a module that contains classes and functions to build neural networks. It provides a way to wrap parameters, functions, and layers in the *torch.nn* modules. Any deep learning model is developed using the subclass of the *torch.nn* module it uses method like forward (input) which returns the output

In [ ]:
import torch 
import torch.nn as nn 

* *nn.Embedding()* is a PyTorch module that is used to store embeddings of a fixed dictionary and size
* *nn.LSTM()* is a module that is used to implement the Long Short-Term Memory (LSTM) network. It is a type of recurrent neural network (RNN) that is capable of learning long-term dependencies.
* *nn.Linear()* is a PyTorch module that is used to implement a linear transformation.

In [ ]:
class TextClassifier(nn.Module):
  def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.rnn = nn.LSTM(embedding_dim, hidden_dim, num_layers=2, batch_first=True)
    self.fc = nn.Linear(hidden_dim, output_dim)

  def forward(self, text):
    embedded = self.embedding(text) 
    out, (hidden, cell) = self.tnn(embedded)
    final_hidden = hidden[-1]
    return self.fc(final_hidden)

In [ ]:
vocab_size = 1000
embedding_dim = 100
hidden_dim = 256
output_dim = 2

model = TextClassifier(vocab_size, embedding_dim, hidden_dim, output_dim)

In [ ]:
model

TextClassifier(
  (embedding): Embedding(1000, 100)
  (rnn): LSTM(100, 256, num_layers=2, batch_first=True)
  (fc): Linear(in_features=256, out_features=2, bias=True)
)

#Tensors in Pytorch

In mathematics, a *tensor* is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space. Tensors may map between different objects such as vectors, scalars, and even other tensors. 
In machine learning, *tensors* are multi-dimensional arrays with a uniform type (called a dtype).

* Scalar: Is a physical quantity that is completely described by its magnitude like **6**, **0.7**, etc.
* Vector: Is a quantity that has both magnitude and direction **[3,4,5]**, **[0.3,2.4,1.5]**.
*Matrix:  Is a rectangular array arranged in rows and columns, which is used to represent a mathematical object or a property of such an object. **[[1, 2],[3,8]]**


In [ ]:
Scalar = torch.randn(1)
Scalar

tensor([-0.8036])

In [ ]:
Vector = torch.zeros(1,6)
Vector

tensor([[0., 0., 0., 0., 0., 0.]])

In [ ]:
Matrix = torch.ones(3,5)
Matrix

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
Tensor = torch.randn(3,4,2)
Tensor

tensor([[[-0.7664, -0.4273],
         [ 0.9795,  0.1799],
         [ 0.1814, -0.6267],
         [ 1.3144, -2.3561]],

        [[-0.1870,  0.2109],
         [ 1.5773,  0.4337],
         [ 0.5309,  0.5429],
         [ 0.5626, -0.4614]],

        [[ 1.0257, -0.9932],
         [-1.0558,  1.1682],
         [ 0.7929,  0.4631],
         [-0.4255,  0.3209]]])

In [ ]:
torch.tensor([[2,2], [3,4]])

tensor([[2, 2],
        [3, 4]])

###Debugging with tensors 

When we work with *tensors* and the operations are invalid we will have one of these three common problems:

* Size or shape 
* The data type
* The device in which the tensor is located

**Shape**: The length (number of elements) of each of the axes of a tensor is called its shape. A scalar has rank 0, a vector has rank 1, and a matrix is rank 2. A particular dimension of a tensor is called an axis or dimension

In [ ]:
print(f"The shape of the matrix is: {Matrix.shape}")
print(f"The shape of the tensor is: {Tensor.shape}")

The shape of the matrix is: torch.Size([3, 5])
The shape of the tensor is: torch.Size([3, 4, 2])


**dtype**: A *torch.dtype* is an object that represents the data type of a *torch.Tensor*. PyTorch has twelve different data types for tensors. The most commonly used data type is torch.float32 which is a 32-bit floating point. 

In [ ]:
print(f"The type of the matrix is: {Matrix.dtype}")
print(f"The tupe of the tensor is: {Tensor.dtype}")

The type of the matrix is: torch.float32
The tupe of the tensor is: torch.float32


In [ ]:
m_float32 = torch.tensor([[1.2,2.7], [6.1,4.9]])
m_int64 = torch.tensor([[3,1], [9,2]])

m_float32.dtype, m_int64.dtype

(torch.float32, torch.int64)

In [ ]:
(m_float32 + m_int64).dtype

torch.float32

In [ ]:
m_int64.to(torch.int8)

tensor([[3, 1],
        [9, 2]], dtype=torch.int8)

**Device**: It is important to know the device when we are using tensors in PyTorch because it determines where the tensor will be stored. PyTorch tensors can be stored on CPU memory or GPU memory.

In [ ]:
m_int64.device

device(type='cpu')

CUDA is a parallel computing platform and application programming interface (API) model created by NVIDIA that allows software developers and scientists to use a CUDA-enabled graphics processing unit (GPU) for general purpose processing.

*torch.cuda.is_available()* is a function in PyTorch that returns a boolean indicating whether CUDA is currently available. 

In [ ]:
torch.cuda.is_available()

True

In [ ]:
if torch.cuda.is_available():
  matrix_gpu = m_int64.to(torch.device("cuda"))

matrix_gpu.device

device(type='cuda', index=0)

In [ ]:
matrix_gpu + m_int64

RuntimeError: ignored